### ISSUE TITLE
TypeError: super() takes at least 1 argument

### ISSUE THREAD

**Issue by chrisspen** [kindlychung/pybeep#2]
Running on Ubuntu 14:

```
$ pip install -e git://github.com/kindlychung/pybeep.git#egg=pybeep
$ python
>>> from pybeep.pybeep import PyVibrate, PyBeep
>>> PyVibrate().beep()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/myproject/.env/src/pybeep/pybeep/pybeep.py", line 43, in __init__
    super().__init__(vibrate_bytes)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by kineticz** [comment]
Only python3 is supported:

```
pip3  install -e git://github.com/kindlychung/pybeep.git#egg=pybeep
Obtaining pybeep from git+git://github.com/kindlychung/pybeep.git#egg=pybeep
  Cloning git://github.com/kindlychung/pybeep.git to ./src/pybeep
Installing collected packages: pybeep
  Running setup.py develop for pybeep
Successfully installed pybeep
```
